name: Deploy Automático via FTP

on:
  push:
    branches:
      - main
      - master

jobs:
  ftp-deploy:
    name: Upload dos Arquivos do Restaurante
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Baixando o código do repositório
      uses: actions/checkout@v4

    - name: 🚀 Subindo arquivos para a hospedagem pessoal
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST_SERVIDOR }}
        username: ${{ secrets.USUARIO_FTP }}
        password: ${{ secrets.SENHA_FTP }}
        port: ${{ secrets.PORTA_FTP }}
        server-dir: ${{ secrets.DIRETORIO_REMOTO }}
        white-list: |
          *.html
